Added missing export of qualityFromDB
On OSx scanning of the network was failing recently since the qualityFromDB function was not available outside the scope of function with error: TypeError: networkUtils.qualityFromDB is not a function.